import { supabase } from '../../utils/supabaseClient'
import { v4 as uuidv4 } from 'uuid'

export default async function handler(req, res){
    const uuid = uuidv4()
    const host = req.body.userid
    const { data, error } = await supabase.from('games').insert({
        "game_version": 1,
        "game_uid": uuid,
        "active_player": 1, 
        "p1_address": host,
        "p2_address": '',
        "p3_address": '',
        "p4_address": '',
        "p5_address": '',
        "p1_rolls": 1,
        "p2_rolls": 0,
        "p3_rolls": 0,
        "p4_rolls": 0,
        "p5_rolls": 0,
        "die1_face": 0,
        "die2_face": 0,
        "die3_face": 0,
        "die4_face": 0,
        "die5_face": 0,
        "die6_face": 0,
        "die7_face": 0,
        "die8_face": 0,
        "die1_state": 0,
        "die2_state": 0,
        "die3_state": 0,
        "die4_state": 0,
        "die5_state": 0,
        "die6_state": 0,
        "die7_state": 0,
        "die8_state": 0,
        "die1_location": 1,
        "die2_location": 1,
        "die3_location": 1,
        "die4_location": 1,
        "die5_location": 1,
        "die6_location": 1,
        "die7_location": 1,
        "die8_location": 1,
        "green_mine": 3,
        "purple_mine": 4,
        "red_mine": 6,
        "blue_mine": 12,
        "black_mine": 60,
        "green_table": 0,
        "purple_table": 0,
        "red_table": 0,
        "blue_table": 0,
        "black_table": 0,
        "green_p1": 0,
        "purple_p1": 0,
        "red_p1": 0,
        "blue_p1": 0,
        "black_p1": 0,
        "green_p2": 0,
        "purple_p2": 0,
        "red_p2": 0,
        "blue_p2": 0,
        "black_p2": 0,
        "green_p3": 0,
        "purple_p3": 0,
        "red_p3": 0,
        "blue_p3": 0,
        "black_p3": 0,
        "green_p4": 0,
        "purple_p4": 0,
        "red_p4": 0,
        "blue_p4": 0,
        "black_p4": 0,
        "green_p5": 0,
        "purple_p5": 0,
        "red_p5": 0,
        "blue_p5": 0,
        "black_p5": 0,
    })
    if (error){ return res.status(400).json({message: error}) }
    res.status(200).json({message: data, uuid: uuid})
}